"""
自愈引擎：五段闭环

1. 规则修复 (Flash low)   - 超时重试、等待条件、网络抖动
2. 向量定位器库 (Flash low) - 从历史成功定位器中找相似
3. LLM 候选 (Flash high)  - 分析失败截图/日志生成修复
4. 重跑验证 (MCP)          - 执行修复后代码
5. 开 PR (Git MCP)         - 自动提交修复

这是 WHartTest 唯一没做好的部分 → 你的核心差异化。
"""
import asyncio
import json
from dataclasses import dataclass, field
from typing import Optional
from apps.agent.router import route, get_cost_tracker
from apps.mcp.client import MCPClient


@dataclass
class HealResult:
    """自愈结果"""
    success: bool
    strategy: str              # "rule" / "vector" / "llm"
    old_locator: str
    new_locator: Optional[str] = None
    confidence: float = 0.0
    retries: int = 0
    error: Optional[str] = None


@dataclass
class FailureContext:
    """失败上下文"""
    test_id: str
    error_message: str
    stack_trace: str
    screenshot_path: Optional[str] = None
    page_url: Optional[str] = None
    html_snippet: Optional[str] = None
    locator: Optional[str] = None


class SelfHealEngine:
    """
    自愈引擎

    Usage:
        engine = SelfHealEngine(retry_budget=3)
        result = await engine.heal(failure)
        if result.success:
            await engine.commit_fix(result)  # 开 PR
    """

    def __init__(self, retry_budget: int = 3):
        self.retry_budget = retry_budget
        self.cost_tracker = get_cost_tracker()

    async def heal(self, failure: FailureContext) -> HealResult:
        """
        执行五段自愈闭环

        成本保护：超过 retry_budget 立即放弃，防止无限循环
        """
        for attempt in range(self.retry_budget):
            # ---- Step 1: 规则修复 (Flash low, 最快最便宜) ----
            result = await self._rule_based_fix(failure)
            if result and result.success:
                result.strategy = "rule"
                result.retries = attempt + 1
                return result

            # ---- Step 2: 向量定位器库 (Flash low) ----
            result = await self._vector_locator_lookup(failure)
            if result and result.success:
                result.strategy = "vector"
                result.retries = attempt + 1
                return result

            # ---- Step 3: LLM 候选生成 (Flash high, 深度思考) ----
            result = await self._llm_candidate(failure)
            if not result:
                continue

            # ---- Step 4: 重跑验证 (MCP) ----
            verified = await self._verify_fix(result, failure)
            if verified:
                result.strategy = "llm"
                result.retries = attempt + 1
                return result

        # 超过预算，放弃
        return HealResult(
            success=False,
            strategy="exhausted",
            old_locator=failure.locator or "",
            error=f"Retry budget ({self.retry_budget}) exhausted",
        )

    async def commit_fix(self, result: HealResult, *, branch: str = None) -> dict:
        """
        Step 5: 自动开 PR (Git MCP)
        将修复后的定位器写入代码并提交
        """
        if not result.success or not result.new_locator:
            return {"status": "skipped"}

        import os
        from pathlib import Path

        # 确定修复文件 (约定: tests/locators/{test_id}.py)
        locator_file = Path(f"tests/locators/{result.test_id}.py")
        locator_file.parent.mkdir(parents=True, exist_ok=True)

        content = f'''# Auto-generated by SelfHealEngine
# Strategy: {result.strategy}
# Confidence: {result.confidence}

LOCATORS = {{
    "original": "{result.old_locator}",
    "healed": "{result.new_locator}",
}}
'''

        branch = branch or f"self-heal/{result.test_id}"

        async with MCPClient() as mcp:
            # 创建分支 + 提交
            await mcp.call_tool("git", "create_branch", {"branch": branch})
            await mcp.call_tool("git", "commit_changes", {
                "files": {str(locator_file): content},
                "message": f"fix(locator): self-heal {result.test_id} via {result.strategy}",
            })
            # 开 PR
            pr = await mcp.call_tool("git", "create_pull_request", {
                "title": f"[Self-Heal] Fix locator in {result.test_id}",
                "body": (
                    f"Auto-generated by SelfHealEngine\n\n"
                    f"- Strategy: {result.strategy}\n"
                    f"- Confidence: {result.confidence}\n"
                    f"- Retries: {result.retries}\n"
                ),
                "branch": branch,
            })

        return {"status": "pr_created", "branch": branch, "pr": pr}

    # ============================================================
    # 五段闭环的具体实现
    # ============================================================

    async def _rule_based_fix(self, failure: FailureContext) -> Optional[HealResult]:
        """
        Step 1: 规则修复 (Flash low)

        常见模式：
        - TimeoutError → 增加等待时间
        - ElementNotVisible → scrollIntoView
        - NetworkError → 重试 (幂等)
        - StaleElementReference → 重新查询
        """
        cfg = route("refine_locator")  # Flash (low)
        # 记录成本
        self.cost_tracker.record(100, 50)

        error = failure.error_message.lower()

        # 超时 → 等待策略
        if "timeout" in error:
            return HealResult(
                success=True,
                strategy="rule",
                old_locator=failure.locator or "",
                new_locator=f"{failure.locator} (wait_for_visible, timeout=10000)",
                confidence=0.7,
            )

        # 元素不可见 → 滚动
        if "not visible" in error or "element not interactable" in error:
            return HealResult(
                success=True,
                strategy="rule",
                old_locator=failure.locator or "",
                new_locator=f"scroll_into_view({failure.locator})",
                confidence=0.6,
            )

        # Stale element → 重新获取
        if "stale" in error:
            return HealResult(
                success=True,
                strategy="rule",
                old_locator=failure.locator or "",
                new_locator=f"page.reload().find({failure.locator})",
                confidence=0.5,
            )

        return None  # 不匹配任何规则，进入下一步

    async def _vector_locator_lookup(self, failure: FailureContext) -> Optional[HealResult]:
        """
        Step 2: 向量定位器库 (Flash low)

        从 Qdrant 检索历史成功的定位器：
        - 相同页面 URL + 相似元素描述 → 推荐定位器
        - 基于 text/role/position 的语义相似度
        """
        cfg = route("refine_locator")  # Flash (low)
        self.cost_tracker.record(200, 100)

        # 从 Qdrant 检索相似定位器
        # 实际实现:
        #   candidates = await qdrant.search(
        #       collection="locator_history",
        #       vector=embed(failure.html_snippet),
        #       filter={"url": failure.page_url},
        #       limit=5,
        #   )
        candidates = []  # TODO: 接入 Qdrant

        if candidates:
            best = candidates[0]
            return HealResult(
                success=True,
                strategy="vector",
                old_locator=failure.locator or "",
                new_locator=best["payload"]["locator"],
                confidence=best["score"],
            )

        return None

    async def _llm_candidate(self, failure: FailureContext) -> Optional[HealResult]:
        """
        Step 3: LLM 候选生成 (Flash high - 深度思考)

        输入：失败日志 + 截图 + 页面 accessibility tree
        输出：候选定位器 + 置信度

        这是唯一需要深度思考 (reasoning=high) 的步骤。
        """
        cfg = route("self_heal_repair")  # Flash (high)
        self.cost_tracker.record(2000, 1000)  # 上下文较大

        # 实际调用:
        # prompt = self._build_heal_prompt(failure)
        # response = await call_llm(cfg, prompt)
        # candidate = parse_locator(response)

        # 示意: 返回修复候选
        candidate = HealResult(
            success=False,  # 需 Step 4 验证
            strategy="llm",
            old_locator=failure.locator or "",
            new_locator=None,
            confidence=0.0,
        )

        if candidate.new_locator:
            candidate.success = True
            candidate.confidence = 0.85

        return candidate

    async def _verify_fix(self, candidate: HealResult, failure: FailureContext) -> bool:
        """
        Step 4: 重跑验证 (MCP)

        用修复后的定位器重新执行测试：
        - 通过 Playwright MCP 跑单个用例
        - 成功 → 自愈成功
        - 失败 → 回到 Step 1 (下一轮)
        """
        async with MCPClient() as mcp:
            result = await mcp.call_tool("playwright", "run_tests", {
                "test_code": self._build_test_with_locator(failure, candidate),
                "test_file": f"/tmp/heal_{failure.test_id}.py",
            })

        # 解析结果
        # result 是 JSON 字符串
        data = json.loads(result) if isinstance(result, str) else result
        return data.get("summary", {}).get("failed", 1) == 0

    def _build_test_with_locator(self, failure: FailureContext, candidate: HealResult) -> str:
        """生成使用修复定位器的测试代码"""
        return f'''
import pytest
from playwright.async_api import Page

@pytest.mark.asyncio
async def test_heal_{failure.test_id}(page: Page):
    await page.goto("{failure.page_url or ""}")
    # 原始定位器: {candidate.old_locator}
    # 修复后定位器: {candidate.new_locator}
    await page.locator("{candidate.new_locator}").click()
'''


# ============================================================
# 便捷入口
# ============================================================
async def heal_failure(
    failure: FailureContext,
    *,
    retry_budget: int = 3,
) -> tuple[HealResult, dict]:
    """
    一键自愈 + 自动开 PR

    Returns:
        (heal_result, pr_result)

    Usage:
        result, pr = await heal_failure(
            FailureContext(test_id="login_001", ...),
            retry_budget=3,
        )
        if result.success:
            print(f"Healed via {result.strategy}, PR: {pr['url']}")
    """
    engine = SelfHealEngine(retry_budget=retry_budget)
    result = await engine.heal(failure)

    pr_result = {}
    if result.success:
        pr_result = await engine.commit_fix(result)

    return result, pr_result


# ============================================================
# Phase F：规则驱动自愈闭环（基于 TestRun / TestStepResult）
# ============================================================
async def run(
    case_id: int,
    failed_step_ids: list[int] | None = None,
    *,
    retry_budget: int | None = None,
) -> dict:
    """
    对一条失败用例执行自愈：分析 → 规则修复 → 重跑验证 → 经验沉淀。

    Returns:
        {"case_id", "healed", "failure_count", "attempts": [...]}
    """
    from asgiref.sync import sync_to_async

    from apps.executor.executor import execute_case
    from apps.testcases.models import TestCase

    from .analyzer import analyze_case
    from .fixer import apply_fix
    from .learner import record

    await sync_to_async(TestCase.objects.get)(pk=case_id)
    features = await sync_to_async(analyze_case)(case_id, failed_step_ids)

    attempts: list[dict] = []
    healed = False

    for feature in features:
        fix = await apply_fix(case_id, feature)

        rerun = None
        success = False
        if fix.success:
            rerun = await execute_case(case_id)
            success = rerun.get("status") == "pass"

        log = await sync_to_async(record)(
            feature.failure_type,
            fix.strategy,
            success,
            testcase_id=case_id,
            detail=f"{fix.detail}; rerun={rerun.get('status') if rerun else 'n/a'}",
        )

        attempts.append({
            "step_id": feature.step_id,
            "failure_type": feature.failure_type,
            "suspect": feature.suspect,
            "strategy": fix.strategy,
            "fix_success": fix.success,
            "old_value": fix.old_value,
            "new_value": fix.new_value,
            "detail": fix.detail,
            "status_after": rerun.get("status") if rerun else None,
            "healed": success,
            "log": log,
            "rag_failures": getattr(feature, "similar_failures", []) or [],
            "rag_hint": getattr(fix, "rag_hint", "") or "",
        })

        if success:
            healed = True
            break

    return {
        "case_id": case_id,
        "healed": healed,
        "failure_count": len(features),
        "attempts": attempts,
    }
