# Generated by Django 6.1.1 on 2026-09-15 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0003_alter_testcase_last_run_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfHealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_pattern', models.CharField(max_length=50)),
                ('fix_strategy', models.CharField(max_length=50)),
                ('attempt_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('last_detail', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_testcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heal_logs', to='testcases.testcase')),
            ],
            options={
                'verbose_name': '自愈日志',
                'verbose_name_plural': '自愈日志',
                'ordering': ['-updated_at'],
                'unique_together': {('failure_pattern', 'fix_strategy')},
            },
        ),
    ]
