# Generated by Django 6.1.1 on 2026-09-15 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0003_alter_testcase_last_run_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, default='', max_length=64)),
                ('goal', models.CharField(blank=True, default='', max_length=500)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('running', '运行中'), ('pass', '通过'), ('fail', '失败'), ('error', '异常'), ('skipped', '跳过')], default='running', max_length=20)),
                ('total_cases', models.IntegerField(default=0)),
                ('passed_cases', models.IntegerField(default=0)),
                ('failed_cases', models.IntegerField(default=0)),
                ('report_json', models.CharField(blank=True, default='', max_length=500)),
                ('report_html', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '执行批次',
                'verbose_name_plural': '执行批次',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField(default=0)),
                ('phase', models.CharField(default='step', max_length=20)),
                ('action', models.CharField(blank=True, default='', max_length=50)),
                ('selector', models.CharField(blank=True, default='', max_length=500)),
                ('value', models.TextField(blank=True, default='')),
                ('expected', models.TextField(blank=True, default='')),
                ('actual', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pass', '通过'), ('fail', '失败'), ('error', '异常'), ('skip', '跳过')], default='pass', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('screenshot_path', models.CharField(blank=True, default='', max_length=500)),
                ('duration_ms', models.IntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='executor.testrun')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='testcases.testcase')),
            ],
            options={
                'verbose_name': '步骤结果',
                'verbose_name_plural': '步骤结果',
                'ordering': ['run_id', 'testcase_id', 'step_index'],
            },
        ),
    ]
