# Generated by Django 6.1.1 on 2026-09-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('preconditions', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('assertions', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(choices=[('P0', 'P0 - 冒烟/核心'), ('P1', 'P1 - 主要功能'), ('P2', 'P2 - 次要/边界')], default='P1', max_length=2)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ['-created_at'],
            },
        ),
    ]
