# Generated by Django 6.1.1 on 2026-09-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='last_run_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testcase',
            name='last_run_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='testcase',
            name='raw_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testcase',
            name='target_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
