# Generated by Django 6.1.1 on 2026-09-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_testcase_last_run_at_testcase_last_run_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='last_run_at',
            field=models.DateTimeField(blank=True, help_text='Deprecated: 见 TestRun / TestStepResult', null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='last_run_log',
            field=models.TextField(blank=True, default='', help_text='Deprecated: 见 TestRun / TestStepResult'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='last_run_status',
            field=models.CharField(blank=True, default='', help_text='Deprecated: 见 TestRun / TestStepResult', max_length=20),
        ),
    ]
