# Generated by Django 6.1.1 on 2026-09-17 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_api_base_url_project_base_url_and_more'),
        ('testcases', '0003_alter_testcase_last_run_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='project_id',
        ),
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcases', to='core.project'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='project_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
