# Generated by Django 6.1.1 on 2026-09-17 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('executor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='api_base_url',
            field=models.CharField(blank=True, default='', help_text='被测 API 根地址', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='base_url',
            field=models.CharField(blank=True, default='', help_text='被测 Web 系统地址', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='swagger_url',
            field=models.CharField(blank=True, default='', help_text='Swagger/OpenAPI 地址', max_length=500),
        ),
        migrations.CreateModel(
            name='RequirementDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('file', models.FileField(upload_to='requirements/')),
                ('file_type', models.CharField(blank=True, default='', max_length=20)),
                ('parsed_scenarios', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', '待解析'), ('parsing', '解析中'), ('parsed', '已解析'), ('generating', '生成中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.project')),
            ],
            options={
                'verbose_name': '需求文档',
                'verbose_name_plural': '需求文档',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestGenerationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('generating', '生成中'), ('executing', '执行中'), ('healing', '自愈中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('total', models.PositiveIntegerField(default=0)),
                ('generated', models.PositiveIntegerField(default=0)),
                ('executed', models.PositiveIntegerField(default=0)),
                ('healed', models.PositiveIntegerField(default=0)),
                ('case_ids', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.requirementdoc')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_batches', to='core.project')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_batches', to='executor.testrun')),
            ],
            options={
                'verbose_name': '生成批次',
                'verbose_name_plural': '生成批次',
                'ordering': ['-created_at'],
            },
        ),
    ]
