# Generated by Django 6.1.1 on 2026-09-17 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_api_base_url_project_base_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_key', models.CharField(blank=True, default='', max_length=64)),
                ('epic', models.CharField(blank=True, default='', max_length=200)),
                ('sprint', models.CharField(blank=True, default='', max_length=100)),
                ('module', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('test_types', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(default='P1', max_length=2)),
                ('story_points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('goal', models.TextField(blank=True, default='')),
                ('benefit', models.TextField(blank=True, default='')),
                ('business_rules', models.JSONField(blank=True, default=list)),
                ('test_data', models.JSONField(blank=True, default=dict)),
                ('acceptance', models.JSONField(blank=True, default=list)),
                ('definition_of_done', models.JSONField(blank=True, default=list)),
                ('automation', models.JSONField(blank=True, default=dict)),
                ('api_ref', models.CharField(blank=True, default='', max_length=300)),
                ('env', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='core.requirementdoc')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='core.project')),
            ],
            options={
                'verbose_name': '需求场景',
                'verbose_name_plural': '需求场景',
                'ordering': ['doc_id', 'id'],
            },
        ),
    ]
