# Generated by Django 6.1.1 on 2026-09-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_llmcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='api_spec',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scenario',
            name='source',
            field=models.CharField(blank=True, default='story', max_length=20),
        ),
    ]
