# Generated by Django 6.1.1 on 2026-09-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scenario_api_spec_scenario_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgenerationbatch',
            name='automated_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testgenerationbatch',
            name='manual_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('xlsx', '手动用例 Excel'), ('pytest', '自动化 pytest 工程'), ('json', 'JSON 全量存档')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('file', models.CharField(blank=True, default='', max_length=500)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='core.testgenerationbatch')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to='core.project')),
            ],
            options={
                'verbose_name': '导出任务',
                'verbose_name_plural': '导出任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
